import { type Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "on-secondary-container": "#005669",
        "on-error-container": "#ffdad6",
        "surface-variant": "#35343a",
        background: "#0e0e13",
        "tertiary-container": "#059eff",
        "primary-container": "#ff6b00",
        "surface-container": "#1f1f25",
        "surface-bright": "#39383e",
        "on-surface": "#e4e1e9",
        "primary-fixed": "#ffdbcc",
        "on-tertiary": "#003257",
        "on-tertiary-fixed-variant": "#00497b",
        "surface-dim": "#131318",
        "on-tertiary-fixed": "#001d35",
        "on-primary-fixed": "#351000",
        "secondary-fixed-dim": "#3cd7ff",
        "inverse-on-surface": "#303036",
        primary: "#ffb693",
        "on-primary": "#561f00",
        "tertiary-fixed-dim": "#9ccaff",
        "on-tertiary-container": "#003357",
        "on-error": "#690005",
        "on-secondary": "#003642",
        "primary-fixed-dim": "#ffb693",
        "secondary-fixed": "#b4ebff",
        "surface-tint": "#ffb693",
        "surface-container-low": "#1b1b20",
        outline: "#a98a7d",
        "surface-container-high": "#2a292f",
        "outline-variant": "#5a4136",
        "surface-container-lowest": "#0e0e13",
        "on-secondary-fixed-variant": "#004e5f",
        "inverse-surface": "#e4e1e9",
        secondary: "#a2e7ff",
        "on-background": "#e4e1e9",
        "error-container": "#93000a",
        "on-primary-container": "#572000",
        "tertiary-fixed": "#d0e4ff",
        "on-primary-fixed-variant": "#7a3000",
        "surface-container-highest": "#35343a",
        tertiary: "#9ccaff",
        "on-secondary-fixed": "#001f27",
        "secondary-container": "#00d2fd",
        "on-surface-variant": "#e2bfb0",
        "inverse-primary": "#a04100",
        surface: "#131318",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-space-grotesk)"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
